### ISSUE TITLE
Database Schemas (MongoDB)

### ISSUE THREAD

**Issue by vipinkhushu** [vipinkhushu/ElementsCulmyca2017Backend#1]

**Comment by RishabhShridhar** [comment]
Interested

**Comment by namansachdeva** [comment]
Interested

**Comment by vipinkhushu** [comment]
@RishabhShridhar @namansachdeva MongoDB pe kaam krna aata h?

**Comment by namansachdeva** [comment]
Database MySQL use kiya hai bas!

**Comment by namansachdeva** [comment]
Database MySQL use kiya hai bas!

**Comment by vipinkhushu** [comment]
@namansachdeva @RishabhShridhar @Vipulmaan  We will have to wait for the final event list of culmyca'17, Its expected to be with us in next couple of days ..... only then we can finalize our database schemas.
