### ISSUE TITLE
Coding The Backend 

### ISSUE THREAD

**Issue by vipinkhushu** [vipinkhushu/ElementsCulmyca2017Backend#2]

**Comment by RishabhShridhar** [comment]
Interested

**Comment by gkashish** [comment]
Interested

**Comment by yatind01** [comment]
Interested

**Comment by namansachdeva** [comment]
Interested

**Comment by vipinkhushu** [comment]
@RishabhShridhar @gkashish @yatind01 @namansachdeva NodeJs Kis Kis ko aata h?

**Comment by namansachdeva** [comment]
NodeJS nahi aata hai.

**Comment by yatind01** [comment]
Nodejs nhi aata

**Comment by vipinkhushu** [comment]
We will have to wait for next couple of days till we get data from BRIXX.....

**Comment by vipinkhushu** [comment]
@Vipulmaan Boilerplate coded and deployed on heroku. 
http://elementsculmyca2017.herokuapp.com/
Master branch has been linked to this deployment
